### ISSUE TITLE
When you add the Mob Spawner?

### ISSUE THREAD

**Issue by jdongel2004** [DarkSystem-PE/DarkSystem#10]
I want to play with Mob spawner..

**Comment by DarkYusuf13** [comment]
I will add it with a small update soon.

**Comment by jdongel2004** [comment]
@DarkYusuf13 Can you add the jenkins site or CircleCi ?

**Comment by DarkYusuf13** [comment]
@jdongel2004 I will add them, phar downloading is not possible with TravisCI.

**Comment by DarkYusuf13** [comment]
@jdongel2004 I will add them, phar downloading is not possible with TravisCI.
