### ISSUE TITLE
The player is automatically flying in a weird way.

### ISSUE THREAD

**Issue by hachkingtohach1** [DarkSystem-PE/DarkSystem#102]
https://youtu.be/UHBZfAPlvHg

**Comment by DarkYusuf13** [comment]
On 32bit aerver host devices, players have this bug. We'll try to fix.

**Comment by hachkingtohach1** [comment]
Ok

Vào 21 thg 12, 2017 23:25, "DarkYusuf13" <notifications@github.com> đã viết:
