### ISSUE TITLE
error

### ISSUE THREAD

**Issue by XoticRealmsOwnerandDev** [DarkSystem-PE/DarkSystem#104]
21.12 10:00:09 [Server] INFO ______           _    _____           _                  
21.12 10:00:09 [Server] INFO |  _  \         | |  /  ___|         | |                  
21.12 10:00:09 [Server] INFO | | | |__ _ _ __| | _\ `--. _   _ ___| |_ ___ _ __ ___   
21.12 10:00:09 [Server] INFO | | | / _` | '__| |/ /`--. \ | | / __| __/ _ \ '_ ` _ \  
21.12 10:00:09 [Server] INFO | |/ / (_| | |  |   </\__/ / |_| \__ \ ||  __/ | | | | | 
21.12 10:00:09 [Server] INFO |___/ \__,_|_|  |_|\_\____/ \__, |___/\__\___|_| |_| |_| 
21.12 10:00:09 [Server] INFO __/   |      
21.12 10:00:09 [Server] INFO |___/         MCPE: v1.x (141)
21.12 10:00:09 [Server] INFO Safe!
21.12 10:00:09 [Server] INFO DarkSystem 6.0  *Redflame*
21.12 10:00:10 [Server] INFO Fatal error: Declaration of pocketmine\plugin\PluginBase::getResource(string $filename) must be compatible with pocketmine\plugin\Plugin::getResource($filename) in phar:///custom.phar/src/pocketmine/plugin/PluginBase.php on line 32

**Comment by DarkYusuf13** [comment]
This is caused by a plugin, maybe DevTools
