### ISSUE TITLE
Win10 bug

### ISSUE THREAD

**Issue by majovec** [DarkSystem-PE/DarkSystem#15]
Minecraft win10 client crashet when players join

**Comment by DarkYusuf13** [comment]
Hmm, did you try on mcpe?

**Comment by nikoskon2003** [comment]
well i join with windows 10 and nothing happens! make sure to download the latest version and try to connect!

**Comment by majovec** [comment]
@nikoskon2003 look on date and i now use Turanic soft ( its a best fr genapi)
