### ISSUE TITLE
When I respawn, I'm die.

### ISSUE THREAD

**Issue by jdongel2004** [DarkSystem-PE/DarkSystem#17]
Every time (respawn) always die.  [ fell to the world and died. ]
Even if I change the world, I die.

I have test with version 1.1.5 and 1.2.3

**Comment by DarkYusuf13** [comment]
Hmm, try to join with another world and write result.

**Comment by jdongel2004** [comment]
I'm okay to change the world PC map.
But.. there are errors in  commands and Beacon.

Notice: Undefined variable: codename§r in /root/pmmp/src/pocketmine/command/defaults/VersionCommand.php on line 47                                 
<09:38:36> DarkSystem 》 INFO: 
<09:39:23> DarkSystem 》 CRITICAL: Error: "Call to a member function getInventory() on null" (EXCEPTION) in "/src/pocketmine/block/Beacon" at line 92

**Comment by DarkYusuf13** [comment]
Thanks, but beacon error caused by pc world. Please use original flat world :)

**Comment by nikoskon2003** [comment]
the beacon & command block inventory is kinda solved and we are looking int the infinite kill loop (if you fall into the void)! for more information look at #59

**Comment by nikoskon2003** [comment]
fixed
