### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by poustmal** [DarkSystem-PE/DarkSystem#18]
DarkSystem Crash Report Wed Oct 25 11:26:49 UTC 2017

Error: Call to undefined method pocketmine\level\Level::spawnLightning()
File: /src/pocketmine/level/weather/Weather
Line: 77
Type: notice

Code:
[68] 			}
[69] 			
[70] 			if(($this->weatherNow >= self::RAINY_THUNDER) and ($this->level->getServer()->lightningTime > 0) and is_int($this->duration / $this->level->getServer()->lightningTime)){
[71] 				$players = $this->level->getPlayers();
[72] 				if(count($players) > 0){
[73] 					$p = $players[array_rand($players)];
[74] 					$x = $p->x + mt_rand(-64, 64);
[75] 					$z = $p->z + mt_rand(-64, 64);
[76] 					$y = $this->level->getHighestBlockAt($x, $z);
[77] 					$this->level->spawnLightning($this->temporalVector->setComponents($x, $y, $z));
[78] 				}
[79] 			}
[80] 		}
[81] 		
[82] 		$this->lastUpdate = $currentTick;
[83] 	}
[84] 
[85] 	public function setWeather($wea, $duration = 12000){
[86] 		$this->level->getServer()->getPluginManager()->callEvent($ev = new WeatherChangeEvent($this->level, $wea, $duration));
[87] 		if(!$ev->isCancelled()){

Backtrace:
#0 /src/pocketmine/Server(2542): pocketmine\level\Level->doTick(integer 3378)
#1 /src/pocketmine/Server(2334): pocketmine\Server->tick(boolean)
#2 /src/pocketmine/Server(1885): pocketmine\Server->tickProcessor(boolean)
#3 /src/pocketmine/Server(1804): pocketmine\Server->run(boolean)
#4 /src/pocketmine/PocketMine(336): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /storage/emulated/0/PocketMine/, string /storage/emulated/0/PocketMine/, string /storage/emulated/0/PocketMine/plugins/, string Bilinmeyen)

DarkSystem Version: 2.2.1 #0 [Protocol 138; API 3.0.1]
PHP Version: 7.0.3
Zend Version: 3.0.0
Operating System: Linux, android

Number of Loaded Worlds: 1
Players Online: 1/25

Loaded Plugins:
ChatFilter 1.1 by onebone API(s) 1.1.0, 1.2.0, 3.0.0-ALPHA7
Slapper 1.3.5 by jojoe77777 API(s) 3.0.0-ALPHA5, 3.0.0-ALPHA6
superBAR 1.6.2 by FaigerSYS API(s) 2.0.0, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7
DeathSound 1.0.0 by MyNET(iTCMega.com) API(s) 2.0.0, 3.0.0, 3.0.0-ALPHA7

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH REPORT===
eNrtWXtz2zYS/yo4JTO170Q9rYd1J8+4jttmxk58tnOZTtRRIRKSEPNVgrSsNPnu99sFSFGJ3fY6
mfurUlyRi93FvneB/trIdaQak+6gMz7ud8ad42YjlCY/z7Ika0x+beTbFMuNOMm1rxrNRqSMkSsC
nckwFHkiijhQSx2rQEQqXyeBSBP/TuURQLNZqO5VOJtd0M9kYlK5iS/0ap3HOl4dHILfsgjD73RI
DNsmTzLwbquoCGWugnanfcW8LsGrbTK/vWPdZs7tjZL5WmXtt/a3la5TYloy/AMkQA+x2JiMRs1G
nkloOXnXeNYRn1PfqOxeZQe9wVHvcPKkkt5JkNxq/+5Ax7laqUz0+6MxKfqs+yTHfv/oM452xTvJ
idMiSUIlY2bSe4pJdzwe/AaTqyzx4bkk2+PWf5pb5ymRsiLe43H0BY+dzw76/eETbOZzP4lNnhV+
fvCtNOoMUWcuEhnAZMnivfLz5h5dkevQzGaXUscXyWpVwwITBJP4nej52nhpWKx0bHb432qEUaS2
Cmb56VOzof5vGfTngh0iWh0ak6UMjWo2/CRQJPBwDHaznL6fQDA8rl7xNupUb3p5cPA8X2vjnbht
XiUbcTIVRoXLyeT69OWrH+e3P7x59eL8+lDIOBAlemgzZaVyF2+HgJVK3aIgiRPRsSTazJFJJWFQ
ZDLXSSza4o+yOjz8lcTuVmLP8udpKLcqM2L6JZcru3Rw+E+i6tWooK6fFCSLIz9kKZl7v4ZH/Imz
w3ons0xu5xmU2VH+xNyP9qkemMo7eRD/EFFuKbzhUVMMj6w0g338Dw7/w1P4w3387WP6/gBbKZN/
GyJyTqHbQ1M8/2DJR/vke5SfxaFbzFWUImnC/yAxEyS5UflZAlCs4txY3lvmbzcY1zagSBsd7wXe
uAw1fikdSM+lW0qZ0LDepAGSlDT0iyzDflSEaZex9Q3zIIPTrzVkWixC7YtlEfscU5DWpcnBcwQ0
BK3CbSq6vU7HOns8/Gz3RyKQA4mS61LGyHWG+cj283tFAaTuwTFWG+H2O1vLeKXcYo0rRNgXxBpu
XHoGIfk3MPNOtDmTsa/CUAUHFPCf/mplf7Wyr9PKmo2VihWSmlpDLGlYbLyQ2d3N1iDdYTbYwCA0
Ae61eq0uIItCh0Fj0kGHyZI88RPQdvvjZkOmGmj9VofRMnkX6gUAnda41QGgcOwvdFw8CFQkGa4T
k4t+q9tpDQcCcXdzeSWurs/PL69uxW2hxKXcin5XdI4ng+6kMxZnN7ei1+kOhZSZvx4egSuNhJPG
CJv28fZBxYGToWMX54kp9wSAX1BJs0QHjapHGlIeWZpjVM1VVjNFDVg3RZc1lAXaeWYoC1EDF/gj
e7IV3hEKi9CF1eiXRfJOL65+OB0RmorlAvncmCCy0J0DlUJ04oU1kyzzF3VAJKmR16SZzfYkCxGO
WL96fXP79vX1xQuANmphdA4dYozg0PQmlGm6p1sJ2Ves3xrsq/Y+eZ+oEX1q2tW0GewrN/yzyhkr
js2c39Gpsc7z1Eza7ZXO18Wi5SdReydnu9QMapsCD9+eXtf0rkD7ig9bvX3Fv5Ma2Xvz401N754L
rN/S/+v4utp9NisF3j39CfPstIFVXlBjusG4E9TTfgfct4xVuWaZy+2r89sDfXt2qVaSuB8+ZaKv
ZIwXN38oLDjUKatlBpWQGiVbLuUtlCuYL9eKisCzXZUTV9WCoMPqLJvFz95iXn/t56I3EN3upNef
DI7Fm9szKj8jQrA8PbLd9HateMrPVhmZT9xptGoMoJ1OHRWzUz7tHnf7PQKuQBhhJJ926C2SD56b
Hqe9ARPRCOZRhVU8v0y9LoE3a2gaapNPk+WSANac3i+FyrbTJK6BMvStEitQxs90yoxsYxMROpgo
DHWEXbfwLq9YnCQPprOi05GjHilnH/t1HS3oqFTVvnb3Naaz0TROskiGzBUKZ1sv1JHOp30MXJcE
pfHOK3i+K6WVcYw9fOVM4kl/rTGyRDRnOh3vtdp4AexAg9G0z1RhmGy8JR8PHJY1oow1JDB7sChZ
lIC1zAI/yard0/vUrQR6udR+EebbqfUZt0qafTFM5rCcmbIGPE5xJJxlSCJ9r7o7uFEqqKGxTb67
OL0lELmolWKe2CRZMP07f6BIkSeekffKicE+99jpHCzLJINtqgByYicxnf28XUw5tZ29bZhB6/o7
7+S0qhjRzqXl4RVZwukqqXIUC1YY5anYz7ZpFY4Pi+TBo1JRWttGgk6nnRZ/awGKwhGhF3sLOp04
fGra1TDV2kYhpeqcP2L34edHgfsf5PFHXpjNKthHfHHAJPKP+8DHiPmLbfg7p7c5eP3seS3eb27Z
fORffhNWqIq4LeY/4+cbRmuLNpOChVsDdD7HL4G+mYuf7ZMjB7o4mFs+LOC/2rMZobex40dBz8yK
dAT0Y/Ul8jmBCKU5J2SiwBsBqgXBSPTI4I+sif0DB/FbH7vf45/fobWbxhQbNokms1g8u11nCkEO
EGpTiANTgZFW0KWFQLwLF0dG451HR/2Bj0xEerZW/p3YJsXnhDjalZ1Qxa2NvtOpCrRsJdmqTW/t
C+TUPFnOX968ng/7x15vTnQGTEtGEzFDx1rNGrTR27Wi8xxd6hj0KEEXPHaoNgIHstjw+G2Xucay
pJADTyoXoBWBute+EjgRBlgAJAJjm9C7Lakzuv3ikpVZF7kIkk3cZD7lHccG9VfgPIqeg6wJ+FKF
jpgC/zYYES2CWScbsgZJrwRagYI9sAMxJZ6eu7UibV178MPEqMDqfUqVVVABom7hZmZxr6X4N7Ud
oHD78dzKToEb2lcKOkDhHCbcLhAMeknHCD0IfRdjQKZ8Nt/p1Ut3U0aO2C14EGsBoXbsz7mOlHxI
darjAk1zSWeclVhsQb+UqOBAd1WnWq2JCfvpXEhTQmRwT30l8Hy0nt2GRRqnHpy1QcdgBny1Zjlg
ZIEESbyNksIgKhCdMJdvKBp86grUbEn5TNEgQKpRDHmF2XP5qyJa0JFxKU7NNvZvpbkTaA538DVH
xOn1q5evvp+IW/Ix+1bHxN4osQqThQyF7bJ2s6ZYFKzaJom/ycVCsRNhY82xANlyGVIgSNrMcxtN
RJfSM1CLYsW5+XIpTkS3yYyqcOLl0qWm5OhcTRnEV5rEqnSUoaOqzAvSxNX+KlZ23XKvJqjSf5Qj
kaQcwn8Y1amP6LHxZI0ccMgwiWdJJnDLvQ6dHjx0kpQIptyIZZZEiMQ6c9g1TspktXvDhfmXoiCf
aBhlr72+PXc+wT93RRVumZGO0pBHF5bN7VzJVkXQKVoxIJrukbbC5yujUlG6FxHUokkSGolz/GES
5QUjUioPCpxpA27pBPeIYLfBPtwOARPwcPFvWMMFxdFut4OumD62TVP06M7ssQWV+61D8CROdTE4
DOi6iYtmWb0U0svuB0Vj68eES2wZBwIzHg92XNU4VMON3BrL2/GptJzF/rqI7zzKLEpQNmxE17qU
UbxmKO3YpaUQJD5xA3JKQysenbx0u5khwOmOkF1B0RZYMd0WjmlL8E1rBrNEVILOrt40QWIMDBEH
Gx3ka5uRNvRLrp5LkuHTgko7brOlrMTApeOCRYILB8Od4iR8qfilfBDyc56pvV5Twc72e3pzPFzL
QKOI7aicENJJwAlhKZ2LCX8ijv63XOBJ3U2UOx+i8yhpxeGZ9wvnunkV5pt81pSzwhahHQYlqRQ0
x6uM3Y4pQwbUkG035GxyUGL2/Y6SqwtVTPLiKtS5v94+QmVLLCOHcsXeJ0Zv+GCV2yoN5y9xyhHV
+YFNg7aGIogwYmNQcXJH46arNoG2DbGmjpM/klvIJe9csZ9xE/W4iNdKCgKg9WUEwE7lxF+FfhOK
wUU0aD3CaC8rKi/4E7ukk8DTMSPAicNOh3D4zcMqIdmDiMcHL4oSQoGhYnSirIJ2XY2i0wezISRu
vx4FRFykE3FsmdsTHFcw7hMlL3AZEZXbkJgO6HUjaaMKyDAZLTQCwqK4g5DtzJOyn6OjSLMu+zUb
x2UPXFvNE8HOTtzPaYCs2jlDqpa2B03XqcZJbkdNd6ETu2erdgSKVc4ChhoV1bbF8wdJeWRfqBcj
XNx9zUS4B16CKU2ewHDv+EyHOkqXwEn6E3FEsw8D4oEjl3rIVUxk9iYUMVy7U6X0rL2m/t6q+QWp
ofp8zzvyMN7SLay9+C1RFj4a27oGoKE4DmRWB7n/j1q9F1lYe126i9kdIK9f+66C+ktUX1rDnvYW
Cy/vjbvSOuLXaGGn9xp6xKfZGuDm6mJPedSyuva5JEXq26eJ0Q/1d5uzhq+lu3y7eq2Wob3VqbNa
R0ldcMMxYOqybWFsvt92T2JAd+09srrw6GZq0DnqjPD4/CWF5eBYLUbD0VJ1R3I4HB0PxseLgd8Z
DYPjpRyPg35whCbQEc/B+2rN7qDLO7oGzZM7FesPeyZ/i4KTqSV7us9YW8nnc77xuz4bked1aq/H
+9bAJKeueHz69F/2xYZc
===END CRASH REPORT===

**Comment by DarkYusuf13** [comment]
Please disable weather
