### ISSUE TITLE
Make slapper plugin compatible with DarkSystem

### ISSUE THREAD

**Issue by poustmal** [DarkSystem-PE/DarkSystem#19]
![screenshot_2017-10-25-20-25-03](https://user-images.githubusercontent.com/22281205/32013209-ed63d4ba-b9c2-11e7-9b0a-0717951a21b1.png)

**Comment by poustmal** [comment]
and it's not plugin problem,because genisyspro,pmmp and many softwares use compoundtag.php not compound.php

**Comment by DarkYusuf13** [comment]
In darksystem 3.0 update will support CompoundTag

**Comment by Amirgta1** [comment]
More important is EssentialsPE

**Comment by DarkYusuf13** [comment]
Everyone! We will open a repository for special DS  plugins!

**Comment by nikoskon2003** [comment]
https://github.com/DarkSystem-Plugins/ here you will find all compatible plugins (not yet but soon)
