### ISSUE TITLE
Ask the owners if Apollo if you can use their auto Updater

### ISSUE THREAD

**Issue by HakerKiller** [DarkSystem-PE/DarkSystem#25]
Ask them please user names are @Fabiansigala and @Hatsune-Miku1012

**Comment by Hatsune-Miku1012** [comment]
they can use it if they want it

**Comment by Fabiansigala** [comment]
Free to use :)

**Comment by DarkYusuf13** [comment]
We dont need auto updater now, but maybe in future :)
NOTE: Searching developers for DarkSystem

**Comment by DarkYusuf13** [comment]
We dont need auto updater now, but maybe in future :)
NOTE: Searching developers for DarkSystem

**Comment by Fabiansigala** [comment]
@DarkYusuf13 I can help

**Comment by DarkYusuf13** [comment]
@Fabiansigala I saw ur message now, LOL. Okay. Contant me on discord. dicord server in readme
