### ISSUE TITLE
need .phar file

### ISSUE THREAD

**Issue by XoticRealmsOwnerandDev** [DarkSystem-PE/DarkSystem#27]
need .phar file

**Comment by flayzer1** [comment]
what?

**Comment by DarkYusuf13** [comment]
You can convert with DevTools or /makeserver

**Comment by XoticRealmsOwnerandDev** [comment]
It says that u need a opensorce console/server to run that command (the plugin is running on a pmmp server that's 1.2)

**Comment by nikoskon2003** [comment]
you have to use the darksystem src not pmmp to create it!
Its a different server software (like pmmp)
to make it just put the src folder where the start.cmd is and start the server, then type 'ms' intto the console and w8 to finish (also type 'help' after 'ms' when the help menu shows up it means it is done!)
the .phar file is located at /plugins/DarkSystem/

**Comment by XoticRealmsOwnerandDev** [comment]
can you explain this a bit more

**Comment by nikoskon2003** [comment]
Open pc>download latest src>start server>do 'ms' in console>do 'help' in console. When you help menu is shown it means the .phar file is created in /plugins/darksystem/darksystem*.phar (the * is the extra staff in the name)

**Comment by XoticRealmsOwnerandDev** [comment]
i have a mcpe server hosting company so this would be on multicraft

**Comment by nikoskon2003** [comment]
ok w8 im compiling the .phar
but in the future i am sure you can do it yourself ;)

**Comment by nikoskon2003** [comment]
http://bit.ly/2nam3sJ here is the .phar

**Comment by XoticRealmsOwnerandDev** [comment]
that link does not work for me bc of how my wifi is 

can u make it some other way

**Comment by nikoskon2003** [comment]
you can join our discord server! the .phar is available on it! https://discord.gg/XYSvPz every so often i update the .phar!

**Comment by nikoskon2003** [comment]
you can get the latest .phar from here: http://jenkins.haniokasai.com/job/DarkSystem-PMMP_12/lastSuccessfulBuild/artifact/artifacts/DarkSystem_PMMP1-2.phar
