### ISSUE TITLE
morph

### ISSUE THREAD

**Issue by Amirgta1** [DarkSystem-PE/DarkSystem#32]
hello
bug in code below:
Warning: Invalid argument supplied for foreach() in C:\Users\AM-HA\Desktop\PocketMine-MP\src\pocketmine\level\Level.php on line 2618

This problem is due to:
    public function moveEntity(Player $player, $entityId){
        $chunk = $player->getLevel()->getChunk($player->getX >> 4, $player->getZ >> 4);
        $player->getLevel()->addEntityMovement(
            $chunk->getX(), $chunk->getZ(),
            $entityId,
            $player->x, $player->y, $player->z,
            $player->yaw, $player->pitch
        );
    }

Can you fix it?

**Comment by DarkYusuf13** [comment]
Okay, but morph has removed in 4.2. You can activate from SimpleCommandMap.php.
