### ISSUE TITLE
Not joinable

### ISSUE THREAD

**Issue by poustmal** [DarkSystem-PE/DarkSystem#35]
Try to join using 1.2.5 and sth will appear when you try to join,and server gives errors if you try to join with 1.1.

**Comment by DarkYusuf13** [comment]
We have no bug like that, but we will look at again. Thx for bug :)

**Comment by nikoskon2003** [comment]
do you have plugins while trying to join? if yes remove them and try again! if you still cannot join install the latest src!

**Comment by poustmal** [comment]
The same error and crash happens when I try to join with 1.1 and 1.2 and tested and without plugins:
<15:33:45> DarkSystem 》 NOTICE: Player data not found for "makairosei0", creating new profile
<15:33:45> DarkSystem 》 CRITICAL: Error: "Call to a member function addEntity() on null" (EXCEPTION) in "/src/pocketmine/entity/Entity" at line 398
<15:33:45> DarkSystem 》 EMERGENCY: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
<15:33:45> DarkSystem 》 EMERGENCY: Please upload the "/storage/emulated/0/PocketMine/crashdumps/CrashDump_Tue_Nov_28-15.33.45-UTC_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
<15:33:45> DarkSystem 》 INFO: Makairosei0[/192.168.2.3:54770] logged out due to Server closed
<15:33:45> DarkSystem 》 INFO: Disabling Plugins...
[PE Server] Server was stopped.

**Comment by nikoskon2003** [comment]
ok download latest src and try again!

**Comment by nikoskon2003** [comment]
if it still doesn't work, download the latest php 7.0 bin
