### ISSUE TITLE
Non-numeric value

### ISSUE THREAD

**Issue by Yexeed** [DarkSystem-PE/DarkSystem#56]
When server enables, i get Warning. Look at screen 
![image](https://user-images.githubusercontent.com/32373441/33231860-2aaa7f24-d20d-11e7-91ed-78de35812dde.png)

**Comment by DarkYusuf13** [comment]
I am fixing now :)

**Comment by DarkYusuf13** [comment]
Caused by your php version.

**Comment by Yexeed** [comment]
Is it possible to fix it just for me? Can you give me tip how to fix it (e.g. some code strings), i will fix it in my own build and will not disturb you again :)
