### ISSUE TITLE
Flying

### ISSUE THREAD

**Issue by knyaz98** [DarkSystem-PE/DarkSystem#58]
Add flying?

**Comment by Yexeed** [comment]
stop creating issues, you can report all your complaints and suggestions in one issue, i think

**Comment by knyaz98** [comment]
@Yexeed ха :D

**Comment by Yexeed** [comment]
what means "ха :D"?

**Comment by knyaz98** [comment]
@Yexeed Вадим, он вроде тебе ответил как фикс ту фигню
