### ISSUE TITLE
fix itemframe and sign

### ISSUE THREAD

**Issue by flayzer** [DarkSystem-PE/DarkSystem#60]
-  ## In the core of the problem was that these units were out of sight of the player.
- just replace the file on this!

![screenshot_20171126-123058](https://user-images.githubusercontent.com/32015623/33238043-2922eb66-d2a6-11e7-9faf-7c057ab085b9.png)

- [x] download: [tilefix.zip](https://github.com/DarkSystem-PE/DarkSystem/files/1503729/tilefix.zip)

- https://github.com/DarkSystem-PE/DarkSystem/tree/master/src/pocketmine/tile

**Comment by dirouc** [comment]
Send pull request)

**Comment by DarkYusuf13** [comment]
Yes

**Comment by nikoskon2003** [comment]
Fixed!
