### ISSUE TITLE
Fix fly and chest/sign

### ISSUE THREAD

**Issue by knyaz98** [DarkSystem-PE/DarkSystem#64]
Not working fly mode, add, and chests are missing things, as already mentioned earlier, signs and chests invisible

**Comment by DarkYusuf13** [comment]
Sign chest invisibility fixed but not tested, fly will be fixed soon.

**Comment by knyaz98** [comment]
@DarkYusuf13 And when will be added the fly? You can date

**Comment by knyaz98** [comment]
@DarkYusuf13 And 1.2 can not be run, attracts the earth

**Comment by DarkYusuf13** [comment]
Because 1.2 movement is buggy. Many server softwares have that bug but we tried to improve moving on 1.2. On Original, players cannot jump :/

**Comment by knyaz98** [comment]
@DarkYusuf13 Okay, wait until you add the fly, and to not disappear enchantments
