### ISSUE TITLE
Fix item enchant

### ISSUE THREAD

**Issue by knyaz98** [DarkSystem-PE/DarkSystem#66]
Of the chests missing items and after rejoining to the server, all zacharovane disappear. Adding to the last post, when it will be added to the fly?

**Comment by DarkYusuf13** [comment]
These bugs are will be fixed in 2-3 days. Thanks for understanding.

**Comment by knyaz98** [comment]
Okay, fast pls)

**Comment by dirouc** [comment]
How much longer to wait, if you do this very quickly, I will be very happy and grateful to you!
