### ISSUE TITLE
New bugs, fix fast pls

### ISSUE THREAD

**Issue by knyaz98** [DarkSystem-PE/DarkSystem#67]
A bug with a chest and a sign left, they disappear. Missing things in the chests. After rejoining lost enchantments. After the crash, um is 0, all of the things that was in gamemodd 1, gamemode now 0. And add already fly, 2 days have passed. Not working PlayerMoveEvent.

**Comment by nikoskon2003** [comment]
75% of all you said are currently fixed!

**Comment by DarkYusuf13** [comment]
PlayerMoveEvent is buggy on 1.2 with android host (if 32-bit)

**Comment by knyaz98** [comment]
@nikoskon2003 now working fly, enchantments, gamemode 1...
