### ISSUE TITLE
Why is it impossible to dissapear a floatingtext entity?

### ISSUE THREAD

**Issue by Yexeed** [DarkSystem-PE/DarkSystem#68]
Like author said in readme, its impossible to dissapearing a floating text entities. But why? Can anyone explain? I just dont see a difference between using particle and using entity cause I cant even change text on it.

**Comment by Yexeed** [comment]
But, actually i can, by closing latest entity and spawning a new one.

**Comment by DarkYusuf13** [comment]
'FloatingText Entity' is only an extra. You can use by plugins but If you dont want, use 'particle'. Why that is impossible? Because particle hacks are used by hackers, we added that feature to go new system. FloatingText entity is a named, invisible entity :) Thanks

**Comment by DarkYusuf13** [comment]
If you wont say something, You can close issue
