### ISSUE TITLE
Краш сервера 

### ISSUE THREAD

**Issue by mrskatpe** [DarkSystem-PE/DarkSystem#70]
[CrashDump_Sun_Dec_3-08.53.52-UTC_2017.log](https://github.com/DarkSystem-PE/DarkSystem/files/1524603/CrashDump_Sun_Dec_3-08.53.52-UTC_2017.log)

**Comment by dirouc** [comment]
@mrskatpe Разработчик не русский.  😄

**Comment by dirouc** [comment]
#59 close this issue
