### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ZezForZip** [DarkSystem-PE/DarkSystem#74]
<20:39:39> DarkSystem 》  CRITICAL: Error: "Call to a member function addEntity() on null" (EXCEPTION)
in "/src/pocketmine/entity/Entity" at line 398
<20:39:39> DarkSystem 》  EMERGENCY: An unrecoverable error has occurred and the server has crashed. C
eating a crash dump
<20:39:39> DarkSystem 》  EMERGENCY: Please upload the "/root/test/Server/crashdumps/CrashDump_Sun_Dec
3-20.39.39-UTC_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Giv
 as much info as you can.

**Comment by Yexeed** [comment]
developers is solving it at moment #59

**Comment by dirouc** [comment]
close.

**Comment by DarkYusuf13** [comment]
Solved
