### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ZezForZip** [DarkSystem-PE/DarkSystem#76]
Fatal error: Uncaught Error: Call to undefined function pocketmine\utils\stream_isatty() in /root/tes
/Server/src/pocketmine/utils/Terminal.php:49
Stack trace:
#0 /root/test/Server/src/pocketmine/utils/Terminal.php(126): pocketmine\utils\Terminal::hasFormatting
odes()
#1 /root/test/Server/src/pocketmine/PocketMine.php(219): pocketmine\utils\Terminal::init()
#2 {main}
  thrown in /root/test/Server/src/pocketmine/utils/Terminal.php on line 49

**Comment by DarkYusuf13** [comment]
Will fix
