### ISSUE TITLE
idk what this means

### ISSUE THREAD

**Issue by XoticRealmsOwnerandDev** [DarkSystem-PE/DarkSystem#79]
04.12 13:21:10 [Multicraft] Server stopped
04.12 13:21:20 [Multicraft] Loading server properties
04.12 13:21:20 [Multicraft] Starting server!
04.12 13:21:20 [Multicraft] Loaded config for "@ Custom PHAR (For MCPE Servers - Place "custom.phar" in base directory)"
04.12 13:21:20 [Multicraft] Updating eula.txt file
04.12 13:21:20 [Multicraft] Failed to obtain process information: NoSuchProcess no process found with pid 23743
04.12 13:21:24 [Server] INFO Notice: Undefined index: class in phar:///custom.phar/src/pocketmine/Server.php on line 327
04.12 13:21:24 [Server] INFO Notice: Undefined index: class in phar:///custom.phar/src/pocketmine/Server.php on line 328
04.12 13:21:24 [Server] INFO ______ _ _____ _
04.12 13:21:24 [Server] INFO | _ \ | | / ___| | |
04.12 13:21:24 [Server] INFO | | | |__ _ _ __| | _\ `--. _ _ ___| |_ ___ _ __ ___
04.12 13:21:24 [Server] INFO | | | / _` | '__| |/ /`--. \ | | / __| __/ _ \ '_ ` _ \
04.12 13:21:24 [Server] INFO | |/ / (_| | | | </\__/ / |_| \__ \ || __/ | | | | |
04.12 13:21:24 [Server] INFO |___/ \__,_|_| |_|\_\____/ \__, |___/\__\___|_| |_| |_|
04.12 13:21:24 [Server] INFO __/ |
04.12 13:21:24 [Server] INFO |___/ MCPE: v1.x (141)
04.12 13:21:24 [Server] INFO DARKBOT: ✔ (v1.0.0)
04.12 13:21:24 [Server] INFO No-lag!
04.12 13:21:24 [Server] INFO DarkSystem 4.4.0 (v1) *Chloropyte*
04.12 13:21:24 [Server] INFO Fatal error: Declaration of pocketmine\plugin\PluginBase::getResource(string $filename) must be compatible with pocketmine\plugin\Plugin::getResource($filename) in phar:///custom.phar/src/pocketmine/plugin/PluginBase.php on line 32

**Comment by DarkYusuf13** [comment]
1. Update DarkSystem
2. Maybe caused by a plugin

We will test.
