### ISSUE TITLE
New bug

### ISSUE THREAD

**Issue by ZezForZip** [DarkSystem-PE/DarkSystem#81]
18:36:36> DarkSystem 》  CRITICAL: Error: "Call to a member function addEntity() on null" (EXCEPTION)
in "/src/pocketmine/entity/Entity" at line 398
<18:36:36> DarkSystem 》  EMERGENCY: An unrecoverable error has occurred and the server has crashed. C
eating a crash dump
<18:36:36> DarkSystem 》  EMERGENCY: Please upload the "/root/test/Server/crashdumps/CrashDump_Mon_Dec
4-18.36.36-UTC_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Giv
 as much info as you can.

**Comment by ZezForZip** [comment]
but I updated a few minutes ago

**Comment by ZezForZip** [comment]
I do not want to criticize but you test things before publishing them

**Comment by DarkYusuf13** [comment]
Hmm 👍 
Try yo join with another world. Know this; this bug is caused by world.

**Comment by ZezForZip** [comment]
Okay
