### ISSUE TITLE
need .phar

### ISSUE THREAD

**Issue by XoticRealmsOwnerandDev** [DarkSystem-PE/DarkSystem#82]
i need the phar file bc idk how to do it with dev tools on my server

i host my server from a hosting company

**Comment by DarkYusuf13** [comment]
Jenkins download in readme,

http://jenkins.haniokasai.com/job/DarkSystem-PMMP_12/lastSuccessfulBuild/artifact/artifacts/DarkSystem_PMMP1-2.phar

**Comment by XoticRealmsOwnerandDev** [comment]
i am having this problem

05.12 14:18:00 [Multicraft] Stopping server!
05.12 14:18:00 [Multicraft] Server ran command Restart
05.12 14:18:00 [Server] INFO [Multicraft] Stop command received.
05.12 14:18:00 [Server] INFO [Multicraft] Server shut down.
05.12 14:18:07 [Multicraft] Server shut down (stopping)
05.12 14:18:07 [Multicraft] Server stopped
05.12 14:18:10 [Multicraft] Loading server properties
05.12 14:18:10 [Multicraft] Starting server!
05.12 14:18:10 [Multicraft] Loaded config for "@ Custom PHAR (For MCPE Servers - Place "custom.phar" in base directory)"
05.12 14:18:10 [Multicraft] Updating eula.txt file
05.12 14:18:10 [Multicraft] Failed to obtain process information: NoSuchProcess no process found with pid 5495
05.12 14:18:14 [Server] INFO Notice: Undefined index: class in phar:///custom.phar/src/pocketmine/Server.php on line 327
05.12 14:18:14 [Server] INFO Notice: Undefined index: class in phar:///custom.phar/src/pocketmine/Server.php on line 328
05.12 14:18:14 [Server] INFO ______           _    _____           _                  
05.12 14:18:14 [Server] INFO |  _  \         | |  /  ___|         | |                  
05.12 14:18:14 [Server] INFO | | | |__ _ _ __| | _\ `--. _   _ ___| |_ ___ _ __ ___   
05.12 14:18:14 [Server] INFO | | | / _` | '__| |/ /`--. \ | | / __| __/ _ \ '_ ` _ \  
05.12 14:18:14 [Server] INFO | |/ / (_| | |  |   </\__/ / |_| \__ \ ||  __/ | | | | | 
05.12 14:18:14 [Server] INFO |___/ \__,_|_|  |_|\_\____/ \__, |___/\__\___|_| |_| |_| 
05.12 14:18:14 [Server] INFO __/  |      
05.12 14:18:14 [Server] INFO |___/         MCPE: v1.x (141)
05.12 14:18:14 [Server] INFO Safe!
05.12 14:18:14 [Server] INFO DarkSystem 5.0.0 (v1)  *Chloropyte*
05.12 14:18:15 [Server] INFO Fatal error: Declaration of pocketmine\plugin\PluginBase::getResource(string $filename) must be compatible with pocketmine\plugin\Plugin::getResource($filename) in phar:///custom.phar/src/pocketmine/plugin/PluginBase.php on line 32
