### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by XoticRealmsOwnerandDev** [DarkSystem-PE/DarkSystem#83]
06.12 10:36:10 [Multicraft] Received stop command
06.12 10:36:11 [Multicraft] Server shut down (stopping)
06.12 10:36:11 [Multicraft] Server stopped
06.12 10:36:14 [Multicraft] Received start command
06.12 10:36:14 [Multicraft] Loading server properties
06.12 10:36:14 [Multicraft] Starting server!
06.12 10:36:14 [Multicraft] Loaded config for "@ Custom PHAR (For MCPE Servers - Place "custom.phar" in base directory)"
06.12 10:36:14 [Multicraft] Updating eula.txt file
06.12 10:36:18 [Server] INFO Notice: Undefined index: class in phar:///custom.phar/src/pocketmine/Server.php on line 327
06.12 10:36:18 [Server] INFO Notice: Undefined index: class in phar:///custom.phar/src/pocketmine/Server.php on line 328
06.12 10:36:18 [Server] INFO Notice: Undefined index: class in phar:///custom.phar/src/pocketmine/Server.php on line 327
06.12 10:36:18 [Server] INFO Notice: Undefined index: class in phar:///custom.phar/src/pocketmine/Server.php on line 328
06.12 10:36:18 [Server] INFO ______           _    _____           _                  
06.12 10:36:18 [Server] INFO |  _  \         | |  /  ___|         | |                  
06.12 10:36:18 [Server] INFO | | | |__ _ _ __| | _\ `--. _   _ ___| |_ ___ _ __ ___   
06.12 10:36:18 [Server] INFO | | | / _` | '__| |/ /`--. \ | | / __| __/ _ \ '_ ` _ \  
06.12 10:36:18 [Server] INFO | |/ / (_| | |  |   </\__/ / |_| \__ \ ||  __/ | | | | | 
06.12 10:36:18 [Server] INFO |___/ \__,_|_|  |_|\_\____/ \__, |___/\__\___|_| |_| |_| 
06.12 10:36:18 [Server] INFO __/  |      
06.12 10:36:18 [Server] INFO |___/         MCPE: v1.x (141)
06.12 10:36:18 [Server] INFO Clean!
06.12 10:36:18 [Server] INFO DarkSystem 5.0.0 (v1)  *Chloropyte*

this is after i renamed my plugins floder just so no plugins would load

*server is shut down and wont come back up

**Comment by XoticRealmsOwnerandDev** [comment]
https://github.com/DarkSystem-PE/DarkSystem/blob/master/src/pocketmine/Server.php#L327

**Comment by DarkYusuf13** [comment]
Hmm rename plugins folder as "plugins" :)

**Comment by XoticRealmsOwnerandDev** [comment]
it auto made a plugin floder that was empty i did this on purpose to test the server software with no plugins

**Comment by nikoskon2003** [comment]
Install the given php version and try again! (And update the software) put only the 'src','bin' and 'start.cmd'(or 'start.ps1' or any 'start.x') in a folder!
