### ISSUE TITLE
crash to update

### ISSUE THREAD

**Issue by flayzer** [DarkSystem-PE/DarkSystem#86]
Fatal error: Uncaught Error: Call to a member function getInterfaces() on null in /home/server3/src/darksystem/crossplatform/CrossPlatform.php:94
Stack trace:
#0 /home/server3/src/pocketmine/Server.php(1364): darksystem\crossplatform\CrossPlatform->__construct(Object(pocketmine\Server))
#1 /home/server3/src/pocketmine/PocketMine.php(350): pocketmine\Server->__construct(Object(BaseClassLoader), Object(pocketmine\utils\MainLogger), '/home/server3/', '/home/server3/', '/home/server3/p...', 'Bilinmeyen')
#2 {main}
  thrown in /home/server3/src/darksystem/crossplatform/CrossPlatform.php on line 94

**Comment by DarkYusuf13** [comment]
Fixing
