### ISSUE TITLE
ClassNotFoundException: "Class darksystem\phpseclib\Crypt\Rijndael

### ISSUE THREAD

**Issue by G2PCraft** [DarkSystem-PE/DarkSystem#87]
<10:38:01> DarkSystem 》 CRITICAL: ClassNotFoundException: "Class darksystem\phpseclib\Crypt\Rijndael does not exist" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 126
<10:38:01> DarkSystem 》 EMERGENCY: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

**Comment by DarkYusuf13** [comment]
Oh, okay. Fixing

**Comment by DarkYusuf13** [comment]
Solved
