### ISSUE TITLE
Notice: Uninitialized string offset: 1098

### ISSUE THREAD

**Issue by G2PCraft** [DarkSystem-PE/DarkSystem#90]
Notice: Uninitialized string offset: 1098 in C:\Users\Administrator\Desktop\LobbyTest\src\pocketmine\nbt\NBT.php on line 419

Notice: Undefined property: pocketmine\nbt\tag\CompoundTag::$Data in C:\Users\Administrator\Desktop\LobbyMainnnnnnnnsss\src\pocketmine\level\format\generic\BaseLevelProvider.php on line 42
<06:37:00> DarkSystem 》 ERROR: Could not load level "SW-Lobby": Invalid level.dat
<06:37:00> DarkSystem 》 CRITICAL: pocketmine\utils\LevelException: "Invalid level.dat" (EXCEPTION) in "/src/pocketmine/level/format/generic/BaseLevelProvider" at line 45

**Comment by G2PCraft** [comment]
I use .MCA

**Comment by DarkYusuf13** [comment]
Oh Im fixing

**Comment by DarkYusuf13** [comment]
Please disable your world because this error may damage that.
