### ISSUE TITLE
What is this error?

### ISSUE THREAD

**Issue by dirouc** [DarkSystem-PE/DarkSystem#93]
![image](https://user-images.githubusercontent.com/34062792/34071155-1dab4c1e-e283-11e7-8299-188ab519ac7d.png)

**Comment by dirouc** [comment]
I'm about formatting the text.

**Comment by DarkYusuf13** [comment]
start.sh is buggy, try a new one.

**Comment by DarkYusuf13** [comment]
but I am not sure

**Comment by nikoskon2003** [comment]
Try using the 'start.cmd'
