### ISSUE TITLE
Corrupts Level.dat on any map loaded.

### ISSUE THREAD

**Issue by linuzo** [DarkSystem-PE/DarkSystem#94]
#### Issue description
First I tried using defaut world map and when the server started it said 
CRITICAL: pocketmine\utils\LevelException: "Invalid level.dat" (EXCEPTION) in "/src/pocketmine/level/format/generic/BaseLevelProvider" at line 45

Then I tried a world I had from our server, it loaded frst time but then second time it said invalid level.dat

so that just says this software is corrupting the level.dat files. 

Needs to be fixed. 
#### Steps to reproduce the issue
Install the server and start it 

#### OS and versions 
* DarkSystem Version: 5.2.0
* PHP: 7.0.2
* Server OS: Ubuntu 
* Game version: 1.2.7

#### Crashreport, backtrace, memory dumps, plugins list or other files

```
```

**Comment by DarkYusuf13** [comment]
Oh, thanks for bug. Fixing!
