### ISSUE TITLE
..

### ISSUE THREAD

**Issue by poustmal** [DarkSystem-PE/DarkSystem#98]
______           _    _____           _                  
    |  _  \         | |  /  ___|         | |                  
    | | | |__ _ _ __| | _\ `--. _   _ ___| |_ ___ _ __ ___   
    | | | / _` | '__| |/ /`--. \ | | / __| __/ _ \ '_ ` _ \  
    | |/ / (_| | |  |   </\__/ / |_| \__ \ ||  __/ | | | | | 
    |___/ \__,_|_|  |_|\_\____/ \__, |___/\__\___|_| |_| |_| 
                                 __/   |      
                                 |___/         MCPE: v1.x (141)
      Safe!
                                      
      DarkSystem 6.0  *Redflame*
      
			
<09:15:20> DarkSystem 》 INFO: Enabling Plugins...
<09:15:20> DarkSystem 》 CRITICAL: ClassNotFoundException: "Class pocketmine\command\defaults\TeleportAllCommand does not exist" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 126
<09:15:20> DarkSystem 》 EMERGENCY: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

**Comment by DarkYusuf13** [comment]
We are uploading that now..
